### PR TITLE
Add podspec

### PR DESCRIPTION
**Pull request by rojo69**

### CODE REVIEW

**Comment by oronbz** [comment]
Hi, is it possible to merge this and update cocoapod?
If you're not able to manage the source, please let contributors do this.

**Comment by rojo69** [comment]
I don't have such rights. Am i supposed to do something more than creating a PR to get things happening?

**Comment by oronbz** [comment]
I was aiming my comment to @chrismiles (:

**Comment by kleinlieu** [comment]
@oronbz I can help you get a new version of pods generated for this project.

**Comment by kleinlieu** [comment]
Here you go @oronbz and @rojo69 :

`CMPopTipView master $ pod search CMPopTipView


-> CMPopTipView (2.3.0)
   Custom UIView for iOS that pops up an animated "bubble" pointing at a button or other view. Useful for popup tips.
   pod 'CMPopTipView', '~> 2.3.0'
   - Homepage: https://github.com/chrismiles/CMPopTipView
   - Source:   https://github.com/chrismiles/CMPopTipView.git
   - Versions: 2.3.0, 2.2.0, 2.1.0, 2.0.0, 1.3.0, 1.2.0, 1.1.0, 1.0.0, 0.0.1 [master repo]`

**Comment by oronbz** [comment]
Thanks a lot @kleinlieu !

**Pull request merged**
