### PR TITLE
Initial tests and travis support

### PR DESCRIPTION
**Pull request by ikhsan**
Participating for [Cocoapod Test Jam](http://blog.cocoapods.org/Prepare-to-Jam/)
- add a bunch of basic tests
- add travis support (don't forget to setup yours and get the badge from it)
- change readme to markdown (I hope you don't mind)
- :tada:

### CODE REVIEW

**Comment by yas375** [comment]
+1 on this! Would be nice to get it merge in.
Thanks in advance!

**Comment by boeung** [comment]
NAVER - http://www.naver.com/
--------------------------------------------

boeung@naver.com 님께 보내신 메일 <Re: [CMPopTipView] Initial tests and travis support (#97)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by kleinlieu** [comment]
Thanks. Looks good.

**Comment by ikhsan** [comment]
Now worries :+1: 

Don't forget to setup the your [Travis CI](https://docs.travis-ci.com/user/for-beginners) to get the sweet badges :wink:

**Pull request merged**
